### ISSUE TITLE
New feature: commit confirmed

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation-community/napalm-panos#43]
See details in the parent issue napalm-automation/napalm-base#214

**Comment by itdependsnetworks** [comment]
I am reviewing if this is possible in panos, but relevant patterns. 
https://github.com/napalm-automation/napalm/pull/1266
https://github.com/napalm-automation/napalm/pull/1291

**Comment by itdependsnetworks** [comment]
There is a revert feature, but seems to be no ability to perform an equivalent of a commit confirmed
