### ISSUE TITLE
"msg": "cannot connect to device: Cannot import \"napalm.panos\"

### ISSUE THREAD

**Issue by modo-dub** [napalm-automation-community/napalm-panos#50]
### Description of Issue/Question
Hi,
I'm trying to use the naplam_install_config module to commit code to a palo alto PA 500 running 7.1.8.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [ ] Yes
- [ ] No

### napalm-panos version
(Paste verbatim output from `pip freeze | grep napalm-panos` between quotes below)

```
pip freeze | grep napalm-panos
napalm-panos==0.4.0
```

### PanOS version
(Paste verbatim output from `show system info` between quotes below)

```

```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
The full traceback is:
  File "/tmp/ansible_Gnb88o/ansible_module_napalm_install_config.py", line 251, in main
    network_driver = get_network_driver(dev_os)
  File "/Library/Python/2.7/site-packages/napalm/base/__init__.py", line 91, in get_network_driver
    install_name=module_install_name

fatal: [10.25.230.90]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "archive_file": null, 
            "commit_changes": true, 
            "config": null, 
            "config_file": "/etc/ansible/pan_templates/10.25.230.90.conf", 
            "dev_os": "panos", 
            "diff_file": null, 
            "get_diffs": true, 
            "hostname": "10.25.230.90", 
            "optional_args": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": null, 
            "replace_config": false, 
            "timeout": 60, 
            "username": "wd_admin"
        }
    }, 

```

**Comment by itdependsnetworks** [comment]
What version of napalm do you have? There has been a split from the community and core drivers, and this may be an issue. 

@dbarrosop does that make sense?

**Comment by modo-dub** [comment]
Here is the versions of napalm I'm using
pip freeze | grep napalm
napalm==2.2.0
napalm-base==1.0.0
napalm-panos==0.4.0

**Comment by Seethaar** [comment]
I have the same issue, my debugs match with that of modo-dub.
I don't have much of a coding background.  But the way I tried invoking is with a python script as following.

Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
>>> driver = get_network_driver('panos')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm/base/__init__.py", line 91, in get_network_driver
    install_name=module_install_name
napalm.base.exceptions.ModuleImportError: Cannot import "napalm.panos". Is the library installed?

**Comment by itdependsnetworks** [comment]
addressed in: https://github.com/napalm-automation/napalm/pull/589 and https://github.com/napalm-automation-community/napalm-panos/pull/51

If you pull down develop branch and install  from there, you should be good to go.

**Comment by modo-dub** [comment]
Thanks for getting back to me so quickly on this guys and for your assistance.  I apologize in advance I'm pretty new to github. I tried downloading the develop branch. I'm pretty sure I did this correctly as the code you look to have updated is the code I see in the panos.py file. However, I look to still be having the same error. I tried running my playbook and using the python cli as done by @Seethaar but I still receive the same error. 

Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
>>> driver = get_network_driver('ios')
>>> driver = get_network_driver('panos')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/napalm/base/__init__.py", line 91, in get_network_driver
    install_name=module_install_name
napalm.base.exceptions.ModuleImportError: Cannot import "napalm.panos". Is the library installed?

As you can see if I choose 'ios' it works correctly.

**Comment by itdependsnetworks** [comment]
There was still an issue, I should have addressed in: https://github.com/napalm-automation-community/napalm-panos/pull/52 

If you pull from devel, it should work

**Comment by Seethaar** [comment]
Thanks for your efforts.

I did a git clone on my host and did not know how to proceed.

But browsing through the scripts, I did this.

`>>>from napalm_panos import PANOSDriver
>>> uat = PANOSDriver('192.168.212.10', 'ramanan', 'test123')
>>> uat.open()
>>> uat_output = uat.get_facts()
>>> import json
>>> print (json.dumps(uat_output,indent=4))
{
    "uptime": 13308663,
    "vendor": "Palo Alto Networks",
    "hostname": "uat-palo",
    "fqdn": "N/A",
    "os_version": "8.x.x",
    "serial_number": "00xxxxxxxxxxxxxxx",
    "model": "PA-VM",
    "interface_list": [
        "ethernet1/1",
        "ethernet1/2",
        "ethernet1/3",
        "ethernet1/4",
        "ethernet1/5",
        "tunnel",
        "tunnel.2",
        "tunnel.3",
        "tunnel.4"
    ]
}
>>> uat.close()`

This is what I wanted to achieve.

Thanks a lot!

**Comment by modo-dub** [comment]
thanks for input everybody. I did similar to what @Seethaar has done and it worked for me.
The only issue I have now is that when I run a commit I get an "Error while commiting config". However, I think this is an issue with the PAN itself as when I look at the config the commit has worked successfully.

**Comment by itdependsnetworks** [comment]
you should be able to do: 
```
from napalm import get_network_driver

ios_device='10.1.100.1'
ios_user='ntc'
ios_password='password'
driver = get_network_driver('panos')
```

Please make sure you install from the repo, e.g. `pip install ./` or `sudo pip install ./` from within the napalm-panos directory. 

For the other issue, can you open a new issue with full error?

**Comment by modo-dub** [comment]
I tried doing a pip install from inside the napalm-panos directory and tried the code you have listed above but I still receive the same ModuleImportError. 

>>> from napalm import get_network_driver
>>> ios_device='10.1.100.1'
>>> ios_user='ntc'
>>> ios_password='password'
>>> driver = get_network_driver('panos')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/napalm/base/__init__.py", line 91, in get_network_driver
    install_name=module_install_name
napalm.base.exceptions.ModuleImportError: Cannot import "napalm.panos". Is the library installed?

**Comment by itdependsnetworks** [comment]
Everything should be good with the latest updates, if there are issues, please let me know.
