### ISSUE TITLE
ACC Risk Factor

### ISSUE THREAD

**Issue by Seethaar** [napalm-automation-community/napalm-panos#57]
### Description of Issue/Question
This is a general question.
I am trying to implement a script for weekly health checks of all the palo alto firewalls that we manage. I use the methods on napalm panos documentation. So far so good. Just wondering if I could pull out the current ACC Risk factor value using any method.

Just an intro on ACC Risk Factor:
This information shows the risk factor over the last 60 minutes based upon information inside the ACC tab.This is a general 'threat temperature' of the traffic. If you find it higher than normal, then you can use the main ACC to drill down and investigate what is causing the temperature to be higher than normal.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [ ] Yes
- [.] No

### napalm-panos version
(Paste verbatim output from `pip freeze | grep napalm-panos` between quotes below)
napalm==2.2.0
napalm-base==1.0.0
napalm-panos==0.4.0
```

```

### PanOS version
(Paste verbatim output from `show system info` between quotes below)

```8.0

```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

```

**Comment by itdependsnetworks** [comment]
Nothing is in place for a method like that. Would start with an agreement on a data model, then someone (you?) would have to submit a PR to add it.

**Comment by itdependsnetworks** [comment]
Will close this until a proposal is made.
