### ISSUE TITLE
get_interfaces() throws exception for subiface

### ISSUE THREAD

**Issue by dragosstan2602** [napalm-automation-community/napalm-panos#61]
### Description of Issue/Question

Hi folks, I kept getting this exception thrown every time i was calling this function for subinterfaces (ethernet1/2.100 for example) or for tunnel interfaces (tunnel.100).

I've managed to make a quick fix for this in case you find it useful. Thanks!

```
    def get_interfaces(self):
        LOOPBACK_SUBIF_DEFAULTS = {
            'is_up': True,
            'is_enabled': True,
            'speed': 0,
            'last_flapped': -1.0,
            'mac_address': '',
            'description': 'N/A'
        }
        **bad_pattern = re.compile(r'(\d+\.\d+)|(\w+\.)')**
        interface_dict = {}
        interface_list = self._extract_interface_list()

        for intf in interface_list:
            interface = {}
            cmd = "<show><interface>{0}</interface></show>".format(intf)
            try:
                self.device.op(cmd=cmd)
                interface_info_xml = xmltodict.parse(self.device.xml_root())
                type(interface_info_xml['response']['result'])
                interface_info_json = json.dumps(interface_info_xml['response']['result']['hw'])
                interface_info = json.loads(interface_info_json)
            except KeyError as err:
                **if bad_pattern.search(intf) and 'hw' in str(err):**
                    # loopback/tunnels/physical sub-ifs don't return a 'hw' key
                    interface_dict[intf] = LOOPBACK_SUBIF_DEFAULTS
                    continue
                raise
```
### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [ x] Yes
- [ ] No

### napalm-panos version
(Paste verbatim output from `pip freeze | grep napalm-panos` between quotes below)

```
napalm-panos==0.5.2
```

### PanOS version
(Paste verbatim output from `show system info` between quotes below)

```
7.1.X, 8.0.X
```

### Steps to Reproduce the Issue
call get_interfaces() on devices with subinterfaces or tunnel ifaces

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/dragos/.virtualenvs/nsm-base/lib/python3.6/site-packages/napalm_panos/panos.py", line 528, in get_interfaces
    interface_info_json = json.dumps(interface_info_xml['response']['result']['hw'])
KeyError: 'hw'
```

**Comment by itdependsnetworks** [comment]
@gjim83 :)

**Comment by gjim83** [comment]
@dragosstan2602 you slacker just post the PR!! 😃

2 things (@itdependsnetworks has the last word tho):

I would change the name of `bad_pattern = re.compile(r'(\d+\.\d+)|(\w+\.)')` to something like `subinterface` so that it's clearer what it means.

I'd also make the regex more specific, something along the lines of `r'(ethernet\d+/\d+|loopback)\.\d+'` adding any other specific patterns that you found where this applies.

**Comment by dragosstan2602** [comment]
@gjim83 - tried that already but I don't have rights to branch out. Hence the issue

**Comment by dragosstan2602** [comment]
Raised the PR so no need for this anymore
