### ISSUE TITLE
Interfaces getter is failing

### ISSUE THREAD

**Issue by shanmukha511** [napalm-automation-community/napalm-panos#63]
### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [ ] Yes
- [ ] No

### napalm-panos version
(Paste verbatim output from `pip freeze | grep napalm-panos` between quotes below)

```

```

### PanOS version
(Paste verbatim output from `show system info` between quotes below)

```

```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

```

**Comment by itdependsnetworks** [comment]
Hi, can you edit the issue to be legible?

**Comment by shanmukha511** [comment]
Hi,
I have palo alto devices and i am runing in salt using napalm of commands like test.ping , net.facts and net.interfaces for some devices net.interfaces working but for other devices getting error like below
Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 167, in call out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/napalm_panos/panos.py", line 528, in get_interfaces interface_info_json = json.dumps(interface_info_xml['response']['result']['hw']) KeyError: u'hw

**Comment by itdependsnetworks** [comment]
@shanmukha511 please follow the template given and provide the standard information.

**Comment by shanmukha511** [comment]
napalm-panos version
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
"napalm-panos==0.5.2"

**Comment by itdependsnetworks** [comment]
And the `show system info`?

**Comment by shanmukha511** [comment]
Please find system info

hostname: test.cn.panos
ip-address: 1.1.1.1
netmask: 255.255.255.0
default-gateway: 10.1.1.1
ip-assignment: static
ipv6-address: unknown
ipv6-link-local-address: fe80::290:bff:fe39:b4ae/64
ipv6-default-gateway:
mac-address: 
time: Wed Mar  6 16:51:53 2019
uptime: 179 days, 3:34:20
family: 5000
model: PA-5050
serial: 002201001508
sw-version: 8.0.10
global-protect-client-package-version: 0.0.0
app-version: 8129-5331
app-release-date: 2019/03/01  15:23:01
av-version: 2900-3410
av-release-date: 2019/02/25  04:00:18
threat-version: 0
threat-release-date: 2019/03/01  15:23:01
wf-private-version: 0
wf-private-release-date: unknown
url-db: paloaltonetworks
wildfire-version: 0
wildfire-release-date: unknown

**Comment by itdependsnetworks** [comment]
I think this is fixed in https://github.com/napalm-automation-community/napalm-panos/pull/62
