### ISSUE TITLE
napalm-panos: 'NoneType' object has no attribute 'values'

### ISSUE THREAD

**Issue by netwninja** [napalm-automation-community/napalm-panos#68]
### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [X ] Yes
- [ ] No

### Setup

napalm-server --------PA-FW

### napalm-panos version
(Paste verbatim output from `pip freeze | grep napalm-panos` between quotes below)

```
napalm==2.5.0
napalm-base==1.0.0
napalm-eos==0.6.1
napalm-ios==0.8.1
napalm-panos==0.5.2
```

### PanOS version
(Paste verbatim output from `show system info` between quotes below)

```
ansible@PA1> show system info | match sw
sw-version: 7.0.1
ansible@PA1> 
```

### Steps to Reproduce the Issue

pip install napalm-panos
Then use the below python script
Tried cloning DEV or master from github and then "pip install ./", no luck.

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
python pan1.py 
Traceback (most recent call last):
  File "pan1.py", line 6, in <module>
    dev_info = dev.get_facts()
  File "/usr/local/lib/python2.7/dist-packages/napalm_panos/panos.py", line 392, in get_facts
    facts['interface_list'] = self._extract_interface_list()
  File "/usr/local/lib/python2.7/dist-packages/napalm_panos/panos.py", line 363, in _extract_interface_list
    for entry_contents in entry.values():
AttributeError: 'NoneType' object has no attribute 'values'
```
### Sample python script 

```
 cat pan1.py 
import json
from napalm import get_network_driver
driver = get_network_driver('panos')
dev = driver(hostname='10.0.0.189', username='ansible', password='ansible123')
dev.open()
dev_info = dev.get_facts()
dev.close()
print(json.dumps(dev_info, sort_keys=True, indent=4))

```

**Comment by netwninja** [comment]
![Screen Shot 2019-10-12 at 9 43 29 AM](https://user-images.githubusercontent.com/45272577/66704877-fe965e00-ecd4-11e9-9e5a-372873a1d2cc.png)

**Comment by netwninja** [comment]
![Screen Shot 2019-10-12 at 9 43 08 AM](https://user-images.githubusercontent.com/45272577/66704880-03f3a880-ecd5-11e9-895f-8a501f850d95.png)

**Comment by itdependsnetworks** [comment]
Please copy verbatim what I had put on slack. As an example, i see that your screenshot is missing the word “all” in there

**Comment by netwninja** [comment]
Sorry, I should have paid more attention. Here you go 

![Screen Shot 2019-10-12 at 10 50 58 AM](https://user-images.githubusercontent.com/45272577/66705645-348c1000-ecde-11e9-82f9-2b34b63ce958.png)
![Screen Shot 2019-10-12 at 10 50 46 AM](https://user-images.githubusercontent.com/45272577/66705646-381f9700-ecde-11e9-813e-e9225539813a.png)

**Comment by itdependsnetworks** [comment]
This indicates there is no interfaces, so this is either a bug, your device somehow has no interfaces, or change in behavior. Can you find a working api that provides the interface information? Please provide the results as well.

**Comment by netwninja** [comment]
Looks like napalm-panos doesn't consider MGMT interface as a legit interface. Now i just added an interface E1/1 , assigned it to a zone and napalm-panos script has started working. 

```
ansible@PA1> show interface all

total configured hardware interfaces: 1

name                    id    speed/duplex/state        mac address       
--------------------------------------------------------------------------------
ethernet1/1             16    1000/full/up              ba:db:ee:fb:ad:10 

aggregation groups: 0


total configured logical interfaces: 1

name                id    vsys zone             forwarding               tag    address                                         
------------------- ----- ---- ---------------- ------------------------ ------ ------------------
ethernet1/1         16    1    Inside           vr:default               0      172.16.10.1/24    

ansible@PA1> 
```

### Here is the napalm script output 

```
~# cat pan1.py 
import json
from napalm import get_network_driver
driver = get_network_driver('panos')
dev = driver(hostname='10.0.0.189', username='ansible', password='ansible123')
dev.open()
dev_info = dev.get_facts()
dev.close()
print(json.dumps(dev_info, sort_keys=True, indent=4))



root@napalm:~# python pan1.py 
{
    "fqdn": "N/A", 
    "hostname": "PA1", 
    "interface_list": [
        "ethernet1/1"
    ], 
    "model": "PA-VM", 
    "os_version": "7.0.1", 
    "serial_number": "unknown", 
    "uptime": 1340, 
    "vendor": "Palo Alto Networks"
}

```
I have tested most of the napalm-panos getters and the one which i have found not working is "get_lldp_neighbors". I will open up a new issue for it.  

Thank you for the help.  I will close this issue.
