### ISSUE TITLE
Commit message raises NotImplementedError

### ISSUE THREAD

**Issue by hkam40k** [napalm-automation-community/napalm-panos#77]
Hello,

Current ``PANOSDriver.commit_config()`` method raises a ``NotImplementedError`` and an error message "commit message not implemented for this platform" if a message is given as a parameter, why is that? It should be possible to give a commit message on the CLI: ``commit description "my comment"``?

Regards.

**Comment by hkam40k** [comment]
Hi, the underlying netmiko library now supports providing a commit message for PANOS devices. Would a PR be appreciated for the PANOSDriver to support a commit comment?

**Comment by itdependsnetworks** [comment]
Yes it would be
