### ISSUE TITLE
napalm show configuration fails in netbox

### ISSUE THREAD

**Issue by bile0026** [napalm-automation-community/napalm-panos#86]
### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [X] Yes
- [ ] No

### napalm-panos version
(Paste verbatim output from `pip freeze | grep napalm-panos` between quotes below)

```
# pip freeze | grep napalm
napalm==3.3.1
napalm-panos==0.5.2
```

### PanOS version
(Paste verbatim output from `show system info` between quotes below)

```
time: Tue Sep  7 16:43:23 2021
uptime: 223 days, 19:21:47
family: 5200
model: PA-5220
cloud-mode: non-cloud
sw-version: 9.1.5
global-protect-client-package-version: 5.2.5
app-version: 8453-6919
app-release-date: 2021/09/02 19:02:37 EDT
av-version: 3832-4343
av-release-date: 2021/09/07 03:04:09 EDT
threat-version: 8453-6919
threat-release-date: 2021/09/02 19:02:37 EDT
wf-private-version: 0
wf-private-release-date: unknown
url-db: paloaltonetworks
wildfire-version: 591853-595041
wildfire-release-date: 2021/09/07 12:30:08 EDT
url-filtering-version: 20210907.20311
global-protect-datafile-version: unknown
global-protect-datafile-release-date: unknown
global-protect-clientless-vpn-version: 0
global-protect-clientless-vpn-release-date: 
logdb-version: 9.1.21
platform-family: 5200
high-speed-log-forwarding-mode: off
vpn-disable-mode: off
multi-vsys: off
operational-mode: normal
device-certificate-status: None
```

### Steps to Reproduce the Issue

Try and add device via onboarding plugin, or access status/configuration tab on palo device manually added to netbox.

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
{"error": "No module named 'napalm_base'", "exception": "ModuleNotFoundError", "netbox_version": "2.11.11", "python_version": "3.6.8"}
```

**Comment by itdependsnetworks** [comment]
@bile0026 I suspect this is since I need to release the latest, it has been on my plate for a while, I just need to figure out how to reenable CI to deploy to PyPI. Apologies for the delay.

**Comment by bile0026** [comment]
> @bile0026 I suspect this is since I need to release the latest, it has been on my plate for a while, I just need to figure out how to reenable CI to deploy to PyPI. Apologies for the delay.

No worries, thanks for the quick response! Anxiously awaiting new release :)

**Comment by derekwood08** [comment]
I’m facing the same issue would love to see this fixed.  Thanks!

**Comment by itdependsnetworks** [comment]
Pypi has been updated.
