### ISSUE TITLE
load_replace_candidate broke in v0.5.3

### ISSUE THREAD

**Issue by nbtnc1** [napalm-automation-community/napalm-panos#94]
### Environment
* Python version:  3.8.5
* napalm version:  3.3.1
* napalm-panos version:  0.5.3

### Expected Behavior
Configuration should have loaded on to the device successfully. 

### Observed Behavior
Error while loading config from {path}.

### Steps to Reproduce
1. Attempt to load a config on to the device using load_replace_candidate

It looks like you removed the else statement from here: https://github.com/napalm-automation-community/napalm-panos/blob/v0.5.3/napalm_panos/panos.py#L206

**Comment by nbtnc1** [comment]
Also need an else on the other if too - https://github.com/napalm-automation-community/napalm-panos/blob/develop/napalm_panos/panos.py#L209

**Comment by itdependsnetworks** [comment]
Will take me a few hours to test, but the logic that was there was a bit complicated, I tried to make it simpler. #97

**Comment by itdependsnetworks** [comment]
Updated, tested, and released 0.5.4. I yanked 0.5.3 (rather than delete) from pypi.
